version: '3'
services:
  nginx:
    container_name: nginx
    image: envrideRegistry.azurecr.io/nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443

  maps:
    container_name: maps
    image: envrideRegistry.azurecr.io/maps:latest
    restart: always
    expose:
      - "8090"

  otherapp:
    container_name: otherapp
    image: envrideRegistry.azurecr.io/otherapp:latest
    restart: always
    expose:
      - "8091"
